---
- name: install certbot
  package: name=certbot state=present
  become: yes
- name: set up a cron job
  cron:
    name: certbot
    minute: 41
    hour: 3
    job: certbot renew --post-hook "systemctl reload httpd" --quiet
    state: present
  become: yes
